
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Problemas de Física - Capacitores y Campos Eléctricos</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        header {
            background: #333;
            color: #fff;
            padding: 10px 20px;
            text-align: center;
        }
        section {
            margin: 20px;
            padding: 20px;
            background: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1, h2 {
            color: #333;
        }
        ul {
            list-style: none;
            padding: 0;
        }
        li {
            margin: 10px 0;
            padding: 10px;
            background: #f9f9f9;
            border: 1px solid #ddd;
            border-radius: 5px;
        }
        footer {
            text-align: center;
            padding: 10px 0;
            background: #333;
            color: #fff;
            position: fixed;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <header>
        <h1>Problemas de Física: Capacitores y Campos Eléctricos</h1>
        <p>Tu fuente de problemas diversos y desafiantes en física.</p>
    </header>
    <section>
        <h2>Problemas de Capacitores</h2>
        <ul>
            <li>
                <strong>Problema 1:</strong> Un capacitor de placas paralelas tiene una separación de <strong>d = 0.005 m</strong> y una diferencia de potencial de <strong>ΔV = 200 V</strong>. 
                <br>Calcula el campo eléctrico <strong>E</strong> entre las placas. 
                <br><em>Extra:</em> ¿Qué ΔV sería necesario para duplicar el campo eléctrico manteniendo la misma distancia?
            </li>
            <li>
                <strong>Problema 2:</strong> Un capacitor con placas separadas por 0.01 m tiene una carga de <strong>q = 3 × 10<sup>-6</sup> C</strong>. 
                <br>Calcula la fuerza eléctrica <strong>F</strong> que actúa sobre la carga si el campo eléctrico es <strong>E = 3 × 10<sup>4</sup> N/C</strong>. 
                <br>Luego, determina la aceleración <strong>a</strong> para una partícula con masa <strong>m = 0.005 kg</strong>.
            </li>
        </ul>
    </section>
    <section>
        <h2>Problemas de Campos Eléctricos</h2>
        <ul>
            <li>
                <strong>Problema 1:</strong> Una carga puntual de <strong>q = 2 × 10<sup>-6</sup> C</strong> se coloca en un campo eléctrico uniforme <strong>E = 5 × 10<sup>3</sup> N/C</strong>. 
                <br>Calcula la fuerza <strong>F</strong> sobre la carga y el trabajo realizado para moverla 0.02 m en la dirección del campo.
            </li>
            <li>
                <strong>Problema 2:</strong> La diferencia de potencial entre dos puntos en un campo uniforme es <strong>ΔV = 500 V</strong>. 
                <br>La distancia entre los puntos es <strong>d = 0.01 m</strong>. Calcula el campo eléctrico <strong>E</strong>.
            </li>
        </ul>
    </section>
    <footer>
        <p>Problemas de Física © 2024 - Creado para fines educativos.</p>
    </footer>
</body>
</html>
